sumc(sumc(LOD0 ));
sumc(sumc(LOD1 ));
sumc(sumc(LOD2 ));
sumc(sumc(LOD3 ));
sumc(sumc(LOD4 ));
sumc(sumc(LOD5 ));
sumc(sumc(LOD6 ));
sumc(sumc(LOD7 ));
sumc(sumc(LOD8 ));
sumc(sumc(LOD9 ));
sumc(sumc(LOD10));
sumc(sumc(LOD11));
sumc(sumc(LOD12));
sumc(sumc(LOD13));
sumc(sumc(LOD14));
sumc(sumc(LOD15));
sumc(sumc(LOD16));
sumc(sumc(LOD17));
sumc(sumc(LOD18));
sumc(sumc(LOD19));
sumc(sumc(LOD20));
sumc(sumc(LOD21));
sumc(sumc(LOD22));
sumc(sumc(LOD23));

/*calculating medium commerical OD's 24 hours*/

sumc(sumc(MOD0 ));
sumc(sumc(MOD1 ));
sumc(sumc(MOD2 ));
sumc(sumc(MOD3 ));
sumc(sumc(MOD4 ));
sumc(sumc(MOD5 ));
sumc(sumc(MOD6 ));
sumc(sumc(MOD7 ));
sumc(sumc(MOD8 ));
sumc(sumc(MOD9 ));
sumc(sumc(MOD10 ));
sumc(sumc(MOD11 ));
sumc(sumc(MOD12 ));
sumc(sumc(MOD13 ));
sumc(sumc(MOD14 ));
sumc(sumc(MOD15 ));
sumc(sumc(MOD16 ));
sumc(sumc(MOD17 ));
sumc(sumc(MOD18 ));
sumc(sumc(MOD19 ));
sumc(sumc(MOD20 ));
sumc(sumc(MOD21 ));
sumc(sumc(MOD22 ));
sumc(sumc(MOD23 ));

/*calculating medium commerical OD's 24 hours*/

sumc(sumc(HOD0 ));
sumc(sumc(HOD1 ));
sumc(sumc(HOD2 ));
sumc(sumc(HOD3 ));
sumc(sumc(HOD4 ));
sumc(sumc(HOD5 ));
sumc(sumc(HOD6 ));
sumc(sumc(HOD7 ));
sumc(sumc(HOD8 ));
sumc(sumc(HOD9 ));
sumc(sumc(HOD10 ));
sumc(sumc(HOD11 ));
sumc(sumc(HOD12 ));
sumc(sumc(HOD13 ));
sumc(sumc(HOD14 ));
sumc(sumc(HOD15 ));
sumc(sumc(HOD16 ));
sumc(sumc(HOD17 ));
sumc(sumc(HOD18 ));
sumc(sumc(HOD19 ));
sumc(sumc(HOD20 ));
sumc(sumc(HOD21 ));
sumc(sumc(HOD22 ));
sumc(sumc(HOD23 ));